#!/usr/bin/env python

import os, sys
from subprocess import Popen
from ConfigParser import ConfigParser

def main():
    lil = ConfigParser()
    lil.read(sys.argv[1])
    path = lil.get('Config','filename')
    dirname = os.path.dirname(path)
    basename = os.path.basename(path)
    # See:
    # http://lilypond.org/doc/v2.13/Documentation/usage/lilypond-output-in-other-programs
    args = ['lilypond', '-dbackend=eps', '-dno-gs-load-fonts',
            '-dinclude-eps-fonts', basename]
    if dirname == '':
        p = Popen(args)
    else:
        p = Popen(args, cwd=dirname)
    p.wait()

if __name__ == '__main__':
    main()
