#!/usr/bin/env python

import os, sys
from ConfigParser import ConfigParser

def main():
    lil = ConfigParser()
    lil.read(sys.argv[1])
    path = lil.get('Config','filename')
    dirname = os.path.dirname(path)
    basename = os.path.basename(path)
    print path, dirname, basename
    os.system('cd %s && lilypond -dbackend=eps -dno-gs-load-fonts -dinclude-eps-fonts %s' % (dirname, basename))

if __name__ == '__main__':
    main()
